### PR TITLE
Fixed PHP 7.2 compatibility with ongr/elasticsearch-bundle upgrade

### PR DESCRIPTION
**Pull request by Edvinas9**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| License | MIT

#### What's in this PR?

PHP 7.2 compatibility (upgraded to compatible ONGR/elasticsearch-bundle)

#### BC Breaks/Deprecations

Personally, not aware of any BC breaks

### CODE REVIEW

**Comment by alexander-schranz** [comment]
Hello @Edvinas9,

thank you for your contribution as mention in #357 we currently support ES2.
Until https://github.com/ongr-io/ElasticsearchBundle/pull/860 is not merged and released we can't do this change. But didn't got any response yet from @saimaz to my PR to fix the php 7.2 compatibility in the ES2 Branch. This is also blocking a release currently for us. So we hopefully get the ongr pull request merged soon.

**Comment by saimaz** [comment]
I just released a [1.2.10](https://github.com/ongr-io/ElasticsearchBundle/releases/tag/v1.2.10) with PHP 7 support.

**Comment by alexander-schranz** [comment]
@saimaz thank you very much!
@Edvinas9 did update the version in your PR and run travis on 7.2 now let see if the tests run successfully.

**Comment by alexander-schranz** [comment]
@Edvinas9 @YetiCGN thank you both to investigate into this issue!

@wachterjohannes fixing php 5.5 on travis will be part of #362

**Pull request merged**
