### PR TITLE
Expand composer lint script and add php-cs-fixer as dev-dependency

### PR DESCRIPTION
**Pull request by niklasnatter**

### CODE REVIEW

**Comment by niklasnatter** [comment]
@luca-rath @alexander-schranz What do you think? Do you see any problems with this?

**Review by luca-rath — APPROVED** [review]
Looks good to me, the only thing that comes to my mind is, that `lint-container` should be executed as often as possible (best case would be on every matrix job) ... But in this specific case, if i remember correctly, it can't be executed with `--prefer-lowest`, because it was implemented in symfony 4.4 ... Just wanted to note that to keep that in mind in the future

**Comment by niklasnatter** [comment]
> But in this specific case, if i remember correctly, it can't be executed with --prefer-lowest, because it was implemented in symfony 4.4

Yes, unfortunately the `lint:container` command is only available in Symfony 4.4 😕

**Comment by luca-rath** [comment]
Do we still need circleci here? If nobody disagrees I would just remove that

**Comment by niklasnatter** [comment]
I think circleci is the only place where we set the `ARTICLE_TEST_CASE` variable at the moment. But would be okay for me to change that in another PR 🙂

**Comment by alexander-schranz** [comment]
@nnatter would not set `ARTICLE_TEST_CASE` in this testcases aslong as we do not migrate circleci tests to github actions.

**Comment by niklasnatter** [comment]
> @nnatter would not set ARTICLE_TEST_CASE in this testcases aslong as we do not migrate circleci tests to github actions.

Yes, as said above - would be okay for me to migrate that in the future, but I dont think we need to do it now 🙂

**Review by alexander-schranz — APPROVED** [review]

**Comment by alexander-schranz** [comment]
Looks fine from my side.

**Pull request merged**
