### PR TITLE
Added automation-info

### PR DESCRIPTION
**Pull request by wachterjohannes**
Main PR https://github.com/sulu/sulu/pull/3076/files

### CODE REVIEW

**Comment by danrot** [comment]
Code looks good to me. @alexander-schranz Can you test and merge it?

**Comment by alexander-schranz** [comment]
ACK works for me on `dev` on `stage`, `prod` environment the branch in sulu/sulu did fail for me seems to be a missing grunt build.

**Comment by wachterjohannes** [comment]
should be fixed

**Comment by alexander-schranz** [comment]
@wachterjohannes works now for `prod`, `stage`. can be merged when sulu/sulu#3076 is finished.

**Pull request merged**
